"options":
  "image":
    "type": "string"
    "default": "ibcndevs/limeds:1.4.13-rc.2"
    "description": |
      The default value will deploy the regular LimeDS docker image. If this refers to a docker image in a private repository, please provide the username and its corresponding secret.
  "username":
    "type": "string"
    "default": ""
    "description": |
      When the image is behind a private repository, this is the username to log into the docker repo.
  "secret":
    "type": "string"
    "default": ""
    "description": |
      When the image is behind a private repository, this is the secret to log into the docker repo.
